### PR TITLE
RSA_SHA224

### PR DESCRIPTION
**Pull request by Kochise**
And made the proper corrections for RSA384. Sorry for the delay.

### CODE REVIEW

**Comment by Kochise** [comment]
Any news about this MR ?

**Comment by soloicesky** [comment]
您好，你的邮件已收到，我会尽快回复你。                               best regards                                      zaixing_liu

**Comment by Kochise** [comment]
Closing, this PR has been open for 4 years now.

**Comment by soloicesky** [comment]
您好，你的邮件已收到，我会尽快回复你。                               best regards                                      zaixing_liu

**Pull request closed without merging**
